---
main_interface:  wlan0
main_gw_addr:    192.168.0.1/24
wired_interface: eth0
wired_ipv4_addr: 192.168.0.129/25
wired_dhcpd:
  startup_waiting_time: 10
  domain_name: 'home.internal'
  pool:
    start: 192.168.0.130
    stop:  192.168.0.250
  pinned_hosts:
    labo-sw:
      mac_addr:  xx:xx:xx:xx:xx:xx:xx
      ipv4_addr: 192.168.0.251
