---
- name: set /etc/network/if-pre-up.d/01routing
  ansible.builtin.template:
    dest: /etc/network/if-pre-up.d/01routing
    src: 01routing-if-pre-up.sh.j2
    mode: 0755
  become: true
- ansible.posix.sysctl:
    name: "{{ item }}"
    value: '1'
  become: true
  with_items:
    - net.ipv4.conf.all.forwarding
    - net.ipv4.conf.all.bc_forwarding
    - net.ipv6.conf.all.forwarding
- name: set /etc/dhcpcd.conf
  ansible.builtin.template:
    dest: /etc/dhcpcd.conf
    src: dhcpcd.conf.j2
    mode: 0664
    group: netdev
  become: true
